[package]
name = "pebble"
version = "0.1.0"
edition = "2024"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"           # We do a lot of casts from usize -> u32

[dependencies]
index_vec = "0.1.4"
miette = { version = "7.5.0", features = ["fancy"] }
symbol_table = { version = "0.4.0", features = ["global"] }
thin-vec = "0.2.13"
